---
version: '2'


services:
  ice-diff-processor:
    build: .
    environment:
      KAFKA_BROKER_URL: broker:29092
      # how long to wait for messages in milliseconds
      LISTENER_TIMEOUT: 60000
      LISTEN_TO_TOPICS: ${ICE_SHEET_TOPIC}
      TOPIC_NAME: ${ICE_SHEET_DIFF_TOPIC}    # Control startup order similarly to the "kafka-create-topics" container above.
      STREAMS_BOOTSTRAP_SERVERS: ignored
      STREAMS_SCHEMA_REGISTRY_HOST: ignored
      STREAMS_SCHEMA_REGISTRY_PORT: ignored
      KAFKA_MUSIC_APP_REST_HOST: ignored
      KAFKA_MUSIC_APP_REST_PORT: ignored
      APP_CLASS: "mt.edu.um.bigdataprocessing22.group3.IceExtentDifference"

networks:
  default:
    external:
      name: kafka-network