FROM cassandra
CMD ["cassandra", "-f"]

#ADD ./*.sh ./
#ADD ./*.sh root/test/
#COPY ["manual_docker-entrypoint.sh", "cassandra_init.sh", "./"]
#RUN ls -la *.sh; chmod +x *.sh; ls -la *.sh
#ENTRYPOINT ["/manual_docker-entrypoint.sh"]
#CMD ["bash", "cassandra_init.sh"]
#CMD ["cqlsh", "-u", "cassandra", "-p", "cassandra"]
