version: '3'

services:
  ice_sheets_predictor:
    container_name: ice_sheets_predictor
    build: .
    environment:
      KAFKA_BROKER_URL: broker:29092
      # how long to wait for messages in milliseconds
      LISTENER_TIMEOUT: 60000
      LISTEN_TO_TOPICS: ${ICE_SHEET_TOPIC}
      TOPIC_NAME: ${ICE_SHEET_PRED_TOPIC}
      POLY_DEGREE: 2

networks:
  default:
    external:
      name: kafka-network