version: '3'

services:
  icesheets:
    container_name: ice_sheet_producer
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: ${ICE_SHEET_TOPIC}
      CONTROL_TOPIC: ${CONTROL_TOPIC}

networks:
  default:
    external:
      name: kafka-network