FROM python:3.8

WORKDIR /usr/app

RUN mkdir ./data
# downloading data when building the container is janky. We should probably download it when starting the producer
# having the data ready is faster for debugging than downloading everytime
RUN wget --ftp-user=anonymous -r -nd ftp://sidads.colorado.edu/DATASETS/NOAA/G02135/south/daily/data/ -P ./data
RUN wget --ftp-user=anonymous -r -nd ftp://sidads.colorado.edu/DATASETS/NOAA/G02135/north/daily/data/ -P ./data
ADD ice_sheets_producer ./

RUN mkdir ./reqs
COPY ./ice_sheets_producer/requirements.txt ./reqs
RUN pip install -r ./reqs/requirements.txt

RUN mkdir ./code
COPY ./ice_sheets_producer/IceSheetsProducer.py ./code
COPY __init__.py ./code/producers/
# copy down here to avoid reßdownloading every time the code changes
COPY BaseProducer.py ./code/producers/


# CMD ["python3", "-u", "send_data.py", "--dataset_name", "SeaIceExtent", "--input_dir", "./data"]
CMD ["python3", "-u", "code/IceSheetsProducer.py", "--input_dir", "./data"]