version: '3.7'
services:

  dashboard:
    build: 
      context: ./
    container_name: ice_sheet_viz dashboard
    hostname: ice_sheet_viz dashboord
    restart: always
    ports:
      - 5000:80
    networks:
      - network 
    

      
networks:
  network:
    driver: bridge