version: '3.7'
services:

  dashboard:
    build: 
      context: ./
    container_name: icesheetviz
    hostname: icesheetviz
    restart: always
    ports:
      - 9042:80
    networks:
      - network 
    

      
networks:
  network:
    driver: bridge