version: '3.7'
services:

  dashboard:
    build: 
      context: ./
    container_name: ${ICE_SHEET_VIZ}_dashboard
    hostname: ${ICE_SHEET_VIZ}_dashboard
    restart: always
    ports:
      - 5000:80
    networks:
      - network 
    

      
networks:
  network:
    driver: bridge