version: '3.7'
services:

  dashboard:
    build: 
      context: ./
    container_name: icesheetviz
    hostname: icesheetviz
    restart: always
    ports:
      - 5000:80
    networks:
      - network 
    

      
networks:
  default:
    external:
      name: kafka-network