version: '3'

services:
  icesheets:
    container_name: ice_sheet_producer
    build:
      context: .
      dockerfile: ice_sheets_producer/Dockerfile-icesheets
    environment:
      KAFKA_BROKER_URL: broker:29092
      TOPIC_NAME: ${ICE_SHEET_TOPIC}
      CONTROL_TOPIC: ${CONTROL_TOPIC}

  caribou:
    container_name: caribou_producer
    build:
      context: .
      dockerfile: caribou_producer/Dockerfile-caribou
    environment:
      KAFKA_BROKER_URL: broker:29092
      TOPIC_NAME: ${CARIBOU_TOPIC}
      CONTROL_TOPIC: ${CONTROL_TOPIC}

  oceanheat:
    container_name: oceanheat
    build:
      context: .
      dockerfile: ocean_heat_producer/Dockerfile-oceanheat
    environment:
      KAFKA_BROKER_URL: broker:29092
      TOPIC_NAME: ${OCEAN_HEAT_TOPIC}
      CONTROL_TOPIC: ${CONTROL_TOPIC}

  globaltemp:
    container_name: globaltemp
    build:
      context: .
      dockerfile: global_temp_producer/Dockerfile-globaltemp
    environment:
      KAFKA_BROKER_URL: broker:29092
      TOPIC_NAME: ${GLOBAL_TEMP_TOPIC}
      CONTROL_TOPIC: ${CONTROL_TOPIC}

networks:
  default:
    external:
      name: kafka-network