FROM cassandra:latest
ENV LANG C.UTF-8

COPY custom_entrypoint.sh /
COPY cassandra_init.sh /
RUN chmod +x custom_entrypoint.sh
RUN chmod +x cassandra_init.sh
ENTRYPOINT ["/cassandra_init.sh"]
CMD ["cassandra", "-f"]
